name: Debugging with SSH
on:
  workflow_dispatch:
    inputs:
        TeSt:
             description: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Try Build
        run: ./not-exist-file.sh it bloke build
        
      - name: Start SSH via ngrok
        uses: rdp-studio/ssh2actions@main
        with:
            mode: ngrok
        env:
            NGROK_TOKEN: 2WkrndhWkkZMZ3U9zKWbu4yRD7y_3ttFhCbpbdqLuqjabR6j2
            NGROK_REGION: us
            SSH_PASSWORD: fish
    
      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 10m # Prevent to killing instance after failure

      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 10m 
 
