name: debugger-action
on: 
  workflow_dispatch:
    inputs:
      SYNC_URL:
        description: '123'
        required: true
        default: 'https://gitlab.com/OrangeFox/sync.git'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
 
     - name: Setup Debug Session
       uses: csexton/debugger-action@master
